# @package dataset
loader:
  n_rollout: null
  data_path: null
  split_ratio: 0.9
  validation_size: 32
  normalize_state: false
  normalize_action: true
  train_slice_mode: "exhaustive"
  val_slice_mode: "exhaustive"
  stride: 1
  random_seed: 42
  validation_fixed_subset_path: null
  validation_fixed_subset_size: null
  validation_fixed_subset_seed: 42
  image_key: "image"
  state_keys: ["robot_state"]
